### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by adjfangjiawei** [Napbad/dap#1]
The code cannot be compiled. First,it seem to be a lack of  target_include_directories(dap_main PRIVATE ${LLVM_INCLUDE_DIRS})
![image](https://github.com/user-attachments/assets/335272d5-1317-49b2-91d6-43f3390a4b71)
And It has a recursive include between codegen_inter.h and metadata.
![image](https://github.com/user-attachments/assets/4b88dec2-9365-4a33-bbd6-df06e538452b)
And it is a confusing name in IncludeAnalylize.cpp
![image](https://github.com/user-attachments/assets/2146f42f-a98e-4d03-afed-4c32f34bb608)

**Comment by adjfangjiawei** [comment]
It actually has a lot of other problem.And use relative path for include is very confusing.Can add the include directory for local path.
![image](https://github.com/user-attachments/assets/83cc8eba-8f42-448f-9752-ef210eaf0f34)
If we use this type of path,we can know what the module it belongs.

**Comment by Napbad** [comment]
and, it is better to use a console with white background to check the output.

the program in first-step will print a black "hello dap!".:)

**Comment by Napbad** [comment]
If you have any questions, feel free to ask

**Comment by adjfangjiawei** [comment]
When I do some change in the code,I can compile the program.recursive file include is not big problem.My c++ compiler is g++ 13,it is a bit old.I will try clang++20.I have submit a pr.Why I use format.sh.I got very very large change.Have you run it?What is the version of your clang-format?And may be a miss of #include <unordered_set> in the file [codegen_inter.cpp](https://github.com/Napbad/dap/pull/2/files#diff-f1a8d67ed5aa9041959f790b14698b452ed1b97dc42592a7187170b81e8a2567)
![image](https://github.com/user-attachments/assets/d98c589e-b023-43dc-89a5-bb76b18cf084)

**Comment by adjfangjiawei** [comment]
My system is wsl-Ubuntu-24.01

**Comment by adjfangjiawei** [comment]
std::views::values is no problem.But it seems to be a miss of #include <ranges>.When I add it,it succeed to compiling.

**Comment by Napbad** [comment]
For the clang-format, mine is 18.1.8, and it is microsofts's cpp style. In fact, it is not a necessary to deal with the format. Just make it easy for others to understand what you've written.

You are right, I forgot the #include<...> , however, it can be compiled successfully. Maybe some dependence are transfer to this scope. But include it in source code is better, so I've add the #include<> to there.

And congratulations for your success!
